// Generated by Finicky Kickstart

module.exports = {
    defaultBrowser: "Safari",
    handlers: [
      {
        // Open any link clicked in Slack in Safari
        match: ({ opener }) =>
          opener.bundleId === "com.tinyspeck.slackmacgap",
        browser: "Google Chrome"
      },
    ]
  }
